# Generated by Django 2.2.9 on 2020-04-10 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(related_name='_user_contacts_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
