# Generated by Django 2.2.9 on 2020-04-10 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_user_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='_user_contacts_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
