# Generated by Django 2.2.9 on 2020-07-22 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_auto_20200501_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contacts',
        ),
        migrations.AddField(
            model_name='user',
            name='contactEmail',
            field=models.ManyToManyField(blank=True, related_name='_user_contactEmail_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
