# Generated by Django 2.2.9 on 2020-07-22 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_auto_20200722_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contactEmail',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_email',
            field=models.ManyToManyField(blank=True, related_name='_user_contact_email_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
