# Generated by Django 2.2.9 on 2020-03-24 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamessage',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_messages+', to=settings.AUTH_USER_MODEL),
        ),
    ]
