# Generated by Django 2.2.9 on 2020-03-24 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_messages', '0002_mediamessage_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMessageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_message_groups+', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='media_message_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
