# Generated by Django 2.2.9 on 2020-03-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_messages', '0003_mediamessagegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamessagegroup',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='mediamessagegroup',
            name='group_name',
            field=models.CharField(max_length=50),
        ),
    ]
