# Generated by Django 2.2.9 on 2020-04-08 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_messages', '0004_auto_20200324_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamessage',
            name='attachment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='mediamessage',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media_messages+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
