# Generated by Django 2.2.9 on 2020-05-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_messages', '0005_auto_20200408_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaMessageGroup',
        ),
    ]
